-- Your SQL goes here

CREATE TABLE "roles"
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    user_id BIGINT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)