-- Your SQL goes here

CREATE TABLE assets
(
    id BIGSERIAL PRIMARY KEY,
    asset_tag_id BIGINT NULL REFERENCES asset_tags(id),       
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)