on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    debug-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Build and Test
              run: |
                docker build -t asset-api .

    release-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Release Build and Test
              run: |
                docker build --build-arg CARGO_FLAGS='--release' -t release-asset-api .